recommend_data = [
    {
        "character": "Amber",
        "role": "MELT DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Shimenawa's Reminiscence (4)"},
            {"order": 2, "set_name": "Wanderer's Troupe (4)"},
            {"order": 3, "set_name": "Crimson Witch of Flames (4)"},
            {
                "order": 4,
                "set_name": "Marechaussee Hunter (2) + Crimson Witch of Flames (2)",
            },
            {"order": 5, "set_name": "Gilded Dreams (4)"},
            {
                "order": 6,
                "set_name": "Crimson Witch of Flames (2) / Marechaussee Hunter (2) + 80 EM set (2)",
            },
            {
                "order": 7,
                "set_name": "Crimson Witch of Flames (2) / Marechaussee Hunter (2) + 18% ATK set (2)",
            },
            {"order": 8, "set_name": "80 EM set (2) + 80 EM set (2)"},
            {"order": 9, "set_name": "18% ATK set (2) + 18% ATK set (2)"},
            {"order": 10, "set_name": "18% ATK set (2) + 80 EM set (2)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Sands - Elemental Mastery",
            "Goblet - Pyro DMG",
            "Circlet - Crit DMG",
        ],
        "sub_stats": ["Crit DMG", "ATK%", "Elemental Mastery", "Flat ATK"],
        "talent_priority": ["Normal Attack", "Skill"],
        "ability_tips": [],
        "equipment": [
            "The First Great Magic (5✩)",
            "Aqua Simulacra (5✩)",
            "Thundering Pulse (5✩)",
            "Skyward Harp (5✩)",
            "Polar Star (5✩)",
            "Slingshot (3✩)",
            "Amos' Bow (5✩)",
            "Hunter's Path (5✩)",
            "Ibis Piercer (4✩) (R5)",
            "Viridescent Hunt (4✩)",
            "Hamayumi (4✩)",
            "Prototype Crescent (4✩)",
            "Song of Stillness (4✩)",
            "Windblume Ode (4✩)",
            "The Stringless (4✩)",
            "Sharpshooter's Oath (3✩)",
            "King's Squire (4✩)",
            "Scion of the Blazing Sun (4✩)",
        ],
    },
    {
        "character": "Amber",
        "role": "SUPPORT",
        "artifact_sets": [
            {"order": 1, "set_name": "Noblesse Oblige (4)"},
            {"order": 2, "set_name": "Instructor (4)"},
            {
                "order": 3,
                "set_name": "+20% Energy Recharge set (2) + 20% Energy Recharge set (2)",
            },
            {"order": 4, "set_name": "The Exile (4)"},
        ],
        "main_stats": [
            "Sands - Energy Recharge",
            "Sands - ATK%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate",
            "Circlet - Crit DMG",
        ],
        "sub_stats": [
            "Energy Recharge",
            "Crit Rate",
            "Crit DMG",
            "ATK%",
            "Elemental Mastery",
            "Flat ATK",
        ],
        "talent_priority": ["Burst", "Skill"],
        "ability_tips": [],
        "equipment": [
            "Elegy for the End (5✩)",
            "Favonius Warbow (4✩)",
            "Sacrificial Bow (4✩)",
            "The Viridescent Hunt (4✩)",
        ],
    },
    {
        "character": "Xiangling",
        "role": "OFF-FIELD DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Emblem of Severed Fate (4)"},
            {"order": 2, "set_name": "Crimson Witch of Flames (4)"},
            {
                "order": 3,
                "set_name": "Noblesse Oblige (2) / Crimson Witch of Flames (2) / +18% ATK set (2) / +80 EM set (2) / Emblem of Severed Fate (2) [Choose Two]",
            },
            {"order": 4, "set_name": "Noblesse Oblige (4)"},
            {"order": 5, "set_name": "The Exile (2) Scholar (2)"},
        ],
        "main_stats": [
            "Sands - Energy Recharge / ATK% / Elemental Mastery",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / DMG",
        ],
        "sub_stats": [
            "Energy Recharge",
            "Crit Rate / DMG",
            "ATK%",
            "Elemental Mastery",
            "Flat ATK",
        ],
        "talent_priority": ["Burst", "Skill"],
        "ability_tips": [
            "A few commonly used teams for pyro Xiangling are:",
            "National Team: Xiangling, Xingqiu, Bennett and a Flex unit (Sucrose/Zhongli/Kazuha/Raiden/Chongyun/etc)",
            "Childe Team: Childe, Xiangling, Bennett and a Flex unit (Sucrose/Zhongli/Venti/Kazuha/etc)",
        ],
        "equipment": [
            "Staff of the Scarlet Sands (5✩)",
            "Staff of Homa (5✩)",
            "Engulfing Lightning (5✩)",
            "The Catch (4✩) [R5]",
            "Primordial Jade Winged-Spear (5✩)",
            "Skyward Spine (5✩)",
            "Calamity Queller (5✩)",
            "Deathmatch (4✩)",
            "Ballad of the Fjords (4✩)",
            "Vortex Vanquisher (5✩)",
            "Wavebreaker's Fin (4✩)",
            "Dragon's Bane (4✩)",
            "Missive Windspear (4✩)",
            "Kitain Cross Spear (4✩)",
            "Lithic Spear (4✩)",
            "Favonius Lance (4✩)",
            "Prototype Starglitter (4✩)",
        ],
    },
    {
        "character": "Bennett",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Crimson Witch of Flames (4)"},
            {
                "order": 2,
                "set_name": "Crimson Witch of Flames (2) +18% ATK set (2) / Noblesse Oblige (2) / +80 EM set (2) [Choose Two]",
            },
            {"order": 3, "set_name": "Thundering Fury (4)"},
        ],
        "main_stats": [
            "Sands - Elemental Mastery / ATK%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / DMG",
        ],
        "sub_stats": [
            "Crit Rate / DMG",
            "Elemental Mastery",
            "ATK%",
            "Energy Recharge",
        ],
        "talent_priority": ["Skill", "Burst", "Normal Attack"],
        "ability_tips": [
            "Bennett's EB grants you a pyro status as long as your characters are within his burst AoE (Cryo in specific, since Pyro > Cryo).",
            "For that, cast EB with Bennett, switch to the character imbued with Cryo and walk on Bennett's Burst field.",
            "Upon entering burst field, the Pyro status will continuously imbue you with Pyro, reacting with other elements on you and eventually removing them.",
        ],
        "equipment": [
            "Mistsplitter Reforged (5✩)",
            "Primordial Jade Cutter (5✩)",
            "Freedom-Sworn (5✩)",
            "Summit Shaper (5✩)",
            "Aquila Favonia (5✩)",
            "Blackcliff Longsword (1 Stack) (4✩)",
            "Iron Sting (4✩) [R5]",
            "The Alley Flash (4✩)",
            "Skyward Blade (5✩)",
            "The Black Sword (4✩)",
            "Iron Sting (4✩)",
            "Festering Desire (4✩)",
            "Prototype Rancour (4✩)",
        ],
    },
    {
        "character": "Xinyan",
        "role": "PHYSICAL DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Pale Flame (2) Bloodstained Chivalry (2)"},
            {"order": 2, "set_name": "Pale Flame (4)"},
            {
                "order": 3,
                "set_name": "Emblem of Severed Fate (2) +25% Physical DMG set (2)",
            },
            {
                "order": 4,
                "set_name": "+25% Physical DMG set (2) / +18% ATK set (2) / Noblesse Oblige (2) / Husk of Opulent Dreams (2) [Choose Two]",
            },
        ],
        "main_stats": [
            "Sands - ATK% / Energy Recharge",
            "Goblet - Physical DMG",
            "Circlet - Crit Rate / DMG",
        ],
        "sub_stats": ["Crit Rate / DMG", "ATK%", "Energy Recharge", "DEF%"],
        "talent_priority": ["Normal Attack", "Burst", "Skill"],
        "ability_tips": [
            "Xinyan's skill grants you a Pyro status upon contact with shield. No matter how many times you switch your characters, it'll still apply Pyro every instance you switch with shield. This allows you to cleanse most elemental statuses that have been applied to you.",
            "If the status doesn't get cleansed, switch on that character one more time with the shield. Some elements, such as Hydro, are not cleansed very efficiently.",
        ],
        "equipment": [
            "Redhorn Stonethresher (5✩)",
            "Skyward Pride (5✩)",
            "Serpent Spine (4✩)",
            "The Unforged (5✩)",
            "Song of Broken Pines (5✩)",
            "Wolf's Gravestone (5✩)",
            "Luxurious Sea-Lord (4✩)",
            "Snow-Tombed Starsilver (4✩)",
            "Prototype Archaic (4✩)",
        ],
    },
    {
        "character": "Yanfei",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Crimson Witch of Flames (4)"},
            {"order": 2, "set_name": "Gilded Dreams (4)"},
            {"order": 3, "set_name": "Wanderer's Troupe (4)"},
            {
                "order": 4,
                "set_name": "Crimson Witch of Flames (2) +18% ATK set (2) / +80 EM set (2)",
            },
            {"order": 5, "set_name": "Shimenawa's Reminiscence (4)"},
            {"order": 6, "set_name": "Retracing Bolide (4)"},
        ],
        "main_stats": [
            "Sands - ATK% / Elemental Mastery",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / DMG",
        ],
        "sub_stats": [
            "Crit Rate / DMG",
            "ATK%",
            "Energy Recharge",
            "Elemental Mastery",
            "Flat ATK",
        ],
        "talent_priority": ["Normal Attack", "Burst", "Skill"],
        "ability_tips": [
            "Yanfei's Ascension 4 Talent does a second hit after a Crit Charge Attack. This scales 80% of your ATK and can trigger reactions as well due to having a separate internal cooldown on its Pyro application."
        ],
        "equipment": [
            "Skyward Atlas (5✩)",
            "Memory of Dust (5✩)",
            "Lost Prayer to the Sacred Winds (5✩)",
            "Kagura's Verity (5✩)",
            "The Widsith (4✩)",
            "Dodoco Tales (4✩) [R5]",
            "Solar Pearl (4✩)",
            "Blackcliff Agate (4✩)",
            "Mappa Mare (4✩)",
        ],
    },
    {
        "character": "Thoma",
        "role": "BURGEON",
        "artifact_sets": [
            {"order": 1, "set_name": "Flower of Paradise Lost (4)"},
            {"order": 2, "set_name": "Gilded Dreams (4)"},
            {
                "order": 3,
                "set_name": "+80 EM set (2) / 80 EM set (2) / Emblem of Severed Fate (2)",
            },
            {"order": 4, "set_name": "Crimson Witch of Flames (4)"},
        ],
        "main_stats": [
            "Sands - Energy Recharge / Elemental Mastery",
            "Goblet - Elemental Mastery",
            "Circlet - Elemental Mastery",
        ],
        "sub_stats": [
            "Energy Recharge",
            "Elemental Mastery",
            "HP%",
            "Flat HP",
            "Crit Rate",
        ],
        "talent_priority": ["Skill", "Burst"],
        "ability_tips": [],
        "equipment": [
            "Kitain Cross Spear (4✩)",
            "Favonius Lance (4✩)",
            "Dragon's Bane (4✩)",
            "Moonpiercer (4✩)",
            "Black Tassel (3✩)",
            "Rightful Reward (4✩)",
        ],
    },
    {
        "character": "Thoma",
        "role": "SUPPORT",
        "artifact_sets": [
            {"order": 1, "set_name": "Noblesse Oblige (4)"},
            {
                "order": 2,
                "set_name": "Tenacity of the Millelith (2) / Emblem of Severed Fate (2) / Vourukasha's Glow (2) [Choose two]",
            },
            {"order": 3, "set_name": "Instructor (4)"},
        ],
        "main_stats": [
            "Sands - Energy Recharge / HP%",
            "Goblet - HP%",
            "Circlet - HP% / Crit Rate",
        ],
        "sub_stats": ["Energy Recharge", "HP%", "Crit Rate", "Flat HP"],
        "talent_priority": ["Skill", "Burst"],
        "ability_tips": [],
        "equipment": [
            "Favonius Lance (4✩)",
            "Engulfing Lightning (5✩)",
            "The Catch (4✩) [R5]",
            "Kitain Cross Spear (4✩)",
            "Prototype Starglitter (4✩)",
            "Skyward Spine (5✩)",
            "Black Tassel (3✩)",
            "Rightful Reward (4✩)",
        ],
    },
    {
        "character": "Chevreuse",
        "role": "ROLE",
        "artifact_sets": [
            {"order": 1, "set_name": "Set Name (4)"},
            {"order": 2, "set_name": "Set Name (2) + Set Name (2)"},
            {"order": 3, "set_name": "Set Name (4)"},
        ],
        "main_stats": ["Sands - STAT", "Goblet - STAT", "Circlet - STAT"],
        "sub_stats": ["Substat 1", "Substat 2", "Substat 3", "Substat 4"],
        "talent_priority": ["Priority 1", "Priority 2"],
        "ability_tips": ["Tip 1", "Tip 2"],
        "equipment": ["Weapon 1 (5✩)", "Weapon 2 (5✩)", "Weapon 3 (4✩)"],
    },
    {
        "character": "Gaming",
        "role": "ROLE",
        "artifact_sets": [
            {"order": 1, "set_name": "Set Name (4)"},
            {"order": 2, "set_name": "Set Name (2) + Set Name (2)"},
            {"order": 3, "set_name": "Set Name (4)"},
        ],
        "main_stats": ["Sands - STAT", "Goblet - STAT", "Circlet - STAT"],
        "sub_stats": ["Substat 1", "Substat 2", "Substat 3", "Substat 4"],
        "talent_priority": ["Priority 1", "Priority 2"],
        "ability_tips": ["Tip 1", "Tip 2"],
        "equipment": ["Weapon 1 (5✩)", "Weapon 2 (5✩)", "Weapon 3 (4✩)"],
    },
    {
        "character": "Diluc",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Crimson Witch of Flames (4)"},
            {
                "order": 2,
                "set_name": "Crimson Witch of Flames (2) + Gladiator's Finale (2)",
            },
            {"order": 3, "set_name": "Gladiator's Finale (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Skill", "Burst"],
        "ability_tips": ["Use skill before burst for optimal rotation."],
        "equipment": [
            "Wolf's Gravestone (5✩)",
            "Skyward Pride (5✩)",
            "Serpent Spine (4✩)",
        ],
    },
    {
        "character": "Hu Tao",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Crimson Witch of Flames (4)"},
            {"order": 2, "set_name": "Shimenawa's Reminiscence (4)"},
            {
                "order": 3,
                "set_name": "Crimson Witch of Flames (2) + Gladiator's Finale (2)",
            },
        ],
        "main_stats": [
            "Sands - HP%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "HP%", "Elemental Mastery"],
        "talent_priority": ["Normal Attack", "Burst", "Skill"],
        "ability_tips": ["Low HP gives bonus damage with her skill."],
        "equipment": ["Staff of Homa (5✩)", "Dragon's Bane (4✩)", "Deathmatch (4✩)"],
    },
    {
        "character": "Klee",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Crimson Witch of Flames (4)"},
            {"order": 2, "set_name": "Lavawalker (4)"},
            {"order": 3, "set_name": "Wanderer's Troupe (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Elemental Mastery"],
        "talent_priority": ["Burst", "Skill", "Normal Attack"],
        "ability_tips": ["Use burst before skill for maximum damage."],
        "equipment": [
            "Lost Prayer to the Sacred Winds (5✩)",
            "Skyward Atlas (5✩)",
            "Solar Pearl (4✩)",
        ],
    },
    {
        "character": "Yoimiya",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Shimenawa's Reminiscence (4)"},
            {"order": 2, "set_name": "Crimson Witch of Flames (4)"},
            {
                "order": 3,
                "set_name": "Shimenawa's Reminiscence (2) + Gladiator's Finale (2)",
            },
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Burst", "Skill"],
        "ability_tips": ["Use normal attacks to trigger passive effects."],
        "equipment": ["Thundering Pulse (5✩)", "Rust (4✩)", "Skyward Harp (5✩)"],
    },
    {
        "character": "Dehya",
        "role": "Tank / Support",
        "artifact_sets": [
            {"order": 1, "set_name": "Tenacity of the Millelith (4)"},
            {"order": 2, "set_name": "Emblem of Severed Fate (4)"},
            {
                "order": 3,
                "set_name": "Tenacity of the Millelith (2) + Emblem of Severed Fate (2)",
            },
        ],
        "main_stats": ["Sands - HP%", "Goblet - HP%", "Circlet - HP%"],
        "sub_stats": ["HP%", "Energy Recharge", "Crit Rate", "Crit DMG"],
        "talent_priority": ["Burst", "Skill"],
        "ability_tips": ["Use burst to mitigate damage and provide team support."],
        "equipment": [
            "The Bell (4✩)",
            "Prototype Starglitter (4✩)",
            "Skyward Pride (5✩)",
        ],
    },
    {
        "character": "Lyney",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Crimson Witch of Flames (4)"},
            {"order": 2, "set_name": "Lavawalker (4)"},
            {"order": 3, "set_name": "Wanderer's Troupe (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Pyro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Elemental Mastery"],
        "talent_priority": ["Burst", "Skill", "Normal Attack"],
        "ability_tips": ["Use burst before skill for maximum damage."],
        "equipment": [
            "Lost Prayer to the Sacred Winds (5✩)",
            "Skyward Atlas (5✩)",
            "Solar Pearl (4✩)",
        ],
    },
    {
        "character": "Arlecchino",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Gladiator's Finale (4)"},
            {"order": 2, "set_name": "Bloodstained Chivalry (4)"},
            {
                "order": 3,
                "set_name": "Gladiator's Finale (2) + Bloodstained Chivalry (2)",
            },
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Physical DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Skill", "Burst"],
        "ability_tips": ["Use normal attacks to maximize damage output."],
        "equipment": [
            "Wolf's Gravestone (5✩)",
            "Skyward Pride (5✩)",
            "Serpent Spine (4✩)",
        ],
    },
    {
        "character": "Fischl",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Thundering Fury (4)"},
            {"order": 2, "set_name": "Thundersoother (4)"},
            {"order": 3, "set_name": "Gladiator's Finale (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Skill", "Burst"],
        "ability_tips": ["Use skill and burst to maximize Electro DMG output."],
        "equipment": ["Skyward Harp (5✩)", "Rust (4✩)", "The Stringless (4✩)"],
    },
    {
        "character": "Beidou",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Thundersoother (4)"},
            {"order": 2, "set_name": "Gladiator's Finale (4)"},
            {"order": 3, "set_name": "Thundering Fury (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Skill", "Burst", "Normal Attack"],
        "ability_tips": ["Use skill to maximize damage and trigger counter."],
        "equipment": [
            "Wolf's Gravestone (5✩)",
            "Serpent Spine (4✩)",
            "Skyward Pride (5✩)",
        ],
    },
    {
        "character": "Lisa",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Thundering Fury (4)"},
            {"order": 2, "set_name": "Noblesse Oblige (2) + Thundering Fury (2)"},
            {"order": 3, "set_name": "Gladiator's Finale (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Elemental Mastery"],
        "talent_priority": ["Burst", "Skill", "Normal Attack"],
        "ability_tips": ["Use burst to maximize AoE Electro damage."],
        "equipment": [
            "Lost Prayer to the Sacred Winds (5✩)",
            "Skyward Atlas (5✩)",
            "Mappa Mare (4✩)",
        ],
    },
    {
        "character": "Keqing",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Thundering Fury (4)"},
            {"order": 2, "set_name": "Gladiator's Finale (4)"},
            {"order": 3, "set_name": "Thundersoother (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Skill", "Burst"],
        "ability_tips": ["Use normal attacks and skill to maximize DPS."],
        "equipment": [
            "Primordial Jade Cutter (5✩)",
            "Lion's Roar (4✩)",
            "The Black Sword (4✩)",
        ],
    },
    {
        "character": "Raiden Shogun",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Emblem of Severed Fate (4)"},
            {"order": 2, "set_name": "Noblesse Oblige (2) + Thundering Fury (2)"},
            {"order": 3, "set_name": "Gladiator's Finale (4)"},
        ],
        "main_stats": [
            "Sands - Energy Recharge",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Energy Recharge", "Crit Rate", "Crit DMG", "ATK%"],
        "talent_priority": ["Burst", "Skill", "Normal Attack"],
        "ability_tips": [
            "Use burst to maximize damage and energy recharge for the team."
        ],
        "equipment": [
            "Engulfing Lightning (5✩)",
            "Skyward Spine (5✩)",
            "The Catch (4✩)",
        ],
    },
    {
        "character": "Yae Miko",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Thundering Fury (4)"},
            {"order": 2, "set_name": "Emblem of Severed Fate (4)"},
            {"order": 3, "set_name": "Gladiator's Finale (2) + Thundering Fury (2)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Elemental Mastery"],
        "talent_priority": ["Burst", "Skill", "Normal Attack"],
        "ability_tips": ["Use burst to maximize damage and energy recharge."],
        "equipment": [
            "Lost Prayer to the Sacred Winds (5✩)",
            "Skyward Atlas (5✩)",
            "The Widsith (4✩)",
        ],
    },
    {
        "character": "Cyno",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Thundering Fury (4)"},
            {"order": 2, "set_name": "Gladiator's Finale (4)"},
            {"order": 3, "set_name": "Thundersoother (4)"},
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Electro DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Skill", "Burst"],
        "ability_tips": ["Use skill to trigger passive effects."],
        "equipment": [
            "Primordial Jade Cutter (5✩)",
            "Lion's Roar (4✩)",
            "The Black Sword (4✩)",
        ],
    },
    {
        "character": "Razor",
        "role": "DPS",
        "artifact_sets": [
            {"order": 1, "set_name": "Gladiator's Finale (4)"},
            {"order": 2, "set_name": "Pale Flame (4)"},
            {
                "order": 3,
                "set_name": "Gladiator's Finale (2) + Bloodstained Chivalry (2)",
            },
        ],
        "main_stats": [
            "Sands - ATK%",
            "Goblet - Physical DMG",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Crit Rate", "Crit DMG", "ATK%", "Energy Recharge"],
        "talent_priority": ["Normal Attack", "Burst", "Skill"],
        "ability_tips": ["Use normal attacks and burst to maximize DPS."],
        "equipment": [
            "Wolf's Gravestone (5✩)",
            "Serpent Spine (4✩)",
            "Prototype Archaic (4✩)",
        ],
    },
    {
        "character": "Sara",
        "role": "Support",
        "artifact_sets": [
            {"order": 1, "set_name": "Emblem of Severed Fate (4)"},
            {"order": 2, "set_name": "Noblesse Oblige (4)"},
            {
                "order": 3,
                "set_name": "Emblem of Severed Fate (2) + Noblesse Oblige (2)",
            },
        ],
        "main_stats": [
            "Sands - Energy Recharge",
            "Goblet - ATK%",
            "Circlet - Crit Rate / Crit DMG",
        ],
        "sub_stats": ["Energy Recharge", "ATK%", "Crit Rate", "Crit DMG"],
        "talent_priority": ["Burst", "Skill"],
        "ability_tips": ["Use burst to provide attack boost to the team."],
        "equipment": [
            "Skyward Harp (5✩)",
            "Elegy for the End (5✩)",
            "Sacrificial Bow (4✩)",
        ],
    },
]
